--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code/
project_pubhost: deveiate.org
project_homepage: http://bitbucket.org/laika/thingfish
gem_pubhost: rubygems.org
project_requirements: 
  cl_xmlserial: ">= 1.1.0"
  redland-bindings: ">= 1.0.8.1"
release_smtphost: mail.faeriemud.org
project_description: "ThingFish is a extensible digital asset manager written in Ruby. It can be used to store chunks of data on the network in an application-independent way, associate the chunks with other chunks through metadata, and then search for the chunk you need later and fetch it again, all through a REST API over HTTP. "
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: 
  pluginfactory: ">=1.0.4"
  uuidtools: ~> 2.0.0
project_summary: An extensible REST-based digital asset management server.
version_file: thingfish.rb
additional_pkgfiles: 
- etc/thingfish.conf.*
- QUICKSTART
- run
- var/www/**/*.rhtml
- var/www/static/*.{png,jpg,gif,css,js}
dev_dependencies: 
  tidy: ">=0"
  sqlite3-ruby: ">= 1.2.4"
  ruby-mp3info: ">=0"
  exifr: ">=0"
  json: ">=0"
  rmagick: ">=0"
  sequel: ">= 2.7.1"
  lockfile: ">= 1.4.3"
authors: 
  Mahlon E. Smith: mahlon@martini.nu
  Michael Granger: ged@FaerieMUD.org
post_install_message: ""
project_name: ThingFish
