--- 
excluded_pkgfiles: []

project_requirements: 
  cl_xmlserial: ">= 1.1.0"
  redland-bindings: ">= 1.0.8.1"
project_pubdir: /usr/local/laika/www/public/thingfish/
project_description: "ThingFish is a extensible digital asset manager written in Ruby. It can be used to store chunks of data on the network in an application-independent way, associate the chunks with other chunks through metadata, and then search for the chunk you need later and fetch it again, all through a REST API over HTTP. "
project_pubhost: opensource.laika.com
project_homepage: http://bitbucket.org/laika/thingfish
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: 
  pluginfactory: ">=1.0.4"
  uuidtools: ~> 2.0.0
release_smtphost: mail.faeriemud.org
project_summary: An extensible REST-based digital asset management server.
project_name: ThingFish
version_file: thingfish.rb
additional_pkgfiles: 
- etc/thingfish.conf.*
- QUICKSTART
- run
- var/www/**/*.rhtml
- var/www/static/*.{png,jpg,gif,css,js}
dev_dependencies: 
  sqlite3-ruby: ">= 1.2.4"
  sequel: ">= 2.7.1"
  ruby-mp3info: ">=0"
  rmagick: ">=0"
  exifr: ">=0"
  lockfile: ">= 1.4.3"
  json: ">=0"
  tidy: ">=0"
authors: 
  Michael Granger: ged@FaerieMUD.org
  Mahlon E. Smith: mahlon@martini.nu
post_install_message: ""
