#!/bin/bash

# This is a little wrapper that starts thingfishd with the config in
# etc/thingfish.conf-testing, like run did originally.

plugin_libs=(plugins/*/lib)
# echo ${plugin_libs[*]}

libflags=''
for libdir in ${plugin_libs[*]}; do
	libflags="-I${libdir} $libflags"
done

# echo "Args are: "
# echo $*

# set -x
exec ruby -Ilib $libflags bin/thingfishd -f etc/thingfish.conf-testing $*

